# Graph Calcu

In [2]:
import tensorflow as tf

#define a variable v in g1
g1=tf.Graph()
with g1.as_default():
    v=tf.get_variable("v",initializer=tf.zeros_initializer(shape=[1]))

#define a variable v in g2
g2=tf.Graph()
with g2.as_default():
    v=tf.get_variable("v",initializer=tf.ones_initializer(shape=[1]))
    
#get v in g1
with tf.Session(graph=g1) as sess:
    tf.initializer_all_variables().run()
    with tf.variable_scope("",reuse=True):
        print(sess.run(tf.get_variable("v")))
        
#get v in g2
with tf.Session(graph=g2) as sess:
    tf.initializer_all_variables().run()
    with tf.variable_scope("",reuse=True):
        print(sess.run(tf.get_variable("v")))
        


TypeError: __init__() got an unexpected keyword argument 'shape'

In [3]:
import tensorflow as tf

a=tf.constant([1.0,2.0],name="a")
b=tf.constant([2.0,3.0],name="b")

result=tf.add(a,b,name="add")
print(result)



Tensor("add:0", shape=(2,), dtype=float32)


In [ ]:
#create a session
sess=tf.Session()

sess.run()
sess.close()



In [ ]:
#creat a sess and use python to assis it
with tf.Session() as sess:
    
    sess.run(..)
#this time we donot need use"sess.close()"

In [5]:
sess=tf.Session()

with sess.as_default():
    print(result.eval())

[ 3.  5.]


In [6]:
sess=tf.Session()
print(sess.run(result))
print(result.eval(session=sess))

[ 3.  5.]
[ 3.  5.]


In [7]:
config=tf.ConfigProto(allow_soft_placement=True,log_device_placement=True)

sess1=tf.InteractiveSession(config=config)
sess2=tf.Session(config=config)

In [9]:
#define a net just forward
import tensorflow as tf

w1=tf.Variable(tf.random_normal([2,3],stddev=1,seed=1))
w2=tf.Variable(tf.random_normal([3,1],stddev=1,seed=1))

x=tf.constant([[0.7,0.9]])

a=tf.matmul(x,w1)
y=tf.matmul(a,w2)

sess=tf.Session()

sess.run(w1.initializer)
sess.run(w2.initializer)

print(sess.run(y))
sess.close()

[[ 3.95757794]]


In [ ]:
#another way to initialize all variable one time
init_op=tf.initializer_all_variables()
sess.run(init_op)


In [12]:
import tensorflow as tf

w1=tf.Variable(tf.random_normal([2,3],stddev=1))
w2=tf.Variable(tf.random_normal([3,1],stddev=1))

x=tf.placeholder(tf.float32,shape=(1,2),name="input")
a=tf.matmul(x,w1)
y=tf.matmul(a,w2)

sess=tf.Session()
init_op=tf.global_variables_initializer()
#init_op=tf.initialize_all_variables()
sess.run(init_op)

#print(sess.run(y))

print(sess.run(y,feed_dict={x:[[0.7,0.9]]}))

[[ 0.05991599]]


In [8]:
#define an example to solve two classes
import tensorflow as tf

from numpy.random import RandomState

batch_size=8

#define parameter
w1=tf.Variable(tf.random_normal([2,3],stddev=1,seed=1))
w2=tf.Variable(tf.random_normal([3,1],stddev=1,seed=1))

#
x=tf.placeholder(tf.float32,shape=(None,2),name='x-input')
y_=tf.placeholder(tf.float32,shape=(None,1),name='y-input')

#define forward net
a=tf.matmul(x,w1)
y=tf.matmul(a,w2)

#define loss function and  banckword 
cross_entropy=-tf.reduce_mean(y_*tf.log(tf.clip_by_value(y,1e-10,1.0)))
train_step=tf.train.AdamOptimizer(0.001).minimize(cross_entropy)

#generate a set
rdm=RandomState(1)
dataset_size=128
X=rdm.rand(dataset_size,2)
Y=[[int(x1+x2<1)]for(x1,x2) in X]

#create a session
with tf.Session() as sess:
    #init_op=tf.initialize_all_variables()
    init_op=tf.global_variables_initializer()
    sess.run(init_op)
    print(sess.run(w1))
    print(sess.run(w2))
    
    STEPS=5000
    for i in range(STEPS):
        start=(i*batch_size)%dataset_size
        end=min(start+batch_size,dataset_size)
    
        sess.run(train_step,feed_dict={x:X[start:end], y_:Y[start:end]})
    
        if i%1000==0:
            total_cross_entropy=sess.run(cross_entropy,feed_dict={x:X,y_:Y})
            print("After %d training step(s), cross entropy on all data is %g"%(i,total_cross_entropy))
    print('\n')
    print(sess.run(w1))
    print(sess.run(w2))

[[-0.81131822  1.48459876  0.06532937]
 [-2.4427042   0.0992484   0.59122431]]
[[-0.81131822]
 [ 1.48459876]
 [ 0.06532937]]
After 0 training step(s), cross entropy on all data is 0.0674925
After 1000 training step(s), cross entropy on all data is 0.0163385
After 2000 training step(s), cross entropy on all data is 0.00907547
After 3000 training step(s), cross entropy on all data is 0.00714436
After 4000 training step(s), cross entropy on all data is 0.00578471


[[-1.96182752  2.58235407  1.68203771]
 [-3.46817183  1.06982315  2.11788988]]
[[-1.82471502]
 [ 2.68546653]
 [ 1.41819501]]


In [ ]:
#define activate function
a=tf.nn.relu(tf.matmul(x,w1)+biases1)
y=tf.nn.relu(tf.matmul(a,w2)+biases2)

In [ ]:
#define cross-entropy
cross_entropy=-tf.reduce_mean(y_*tf.log(tf.clip_by_value(y,1e-10,1.0)))

In [ ]:
v=tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(tf.clip_by_value(v,2.5,4.5).eval())
#expected output is:[[2.5,2.5,3.][4,4.5,4.5]]

In [15]:
v1=tf.constant([[1.0,2.0],[3.0,4.0]])
v2=tf.constant([[5.0,6.0],[7.0,8.0]])

print(v1*v2)

print(tf.matmul(v1,v2))

Tensor("mul_11:0", shape=(2, 2), dtype=float32)
Tensor("MatMul_14:0", shape=(2, 2), dtype=float32)


In [ ]:
v=tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(tf.reduce_mean(v).eval())
#expected out is 3.5



#multil
cross_entropy=tf.nn.softmax_cross_entropy_with_logits(y,y_)

#
mse=tf.reduce_mean(tf.square(y_-y))

In [ ]:
#define a loss function
loss=tf.reduce_sum(tf.where(tf.greater(v1,v2),(v1-v2)*a,(v2-v1)*b))

#when the first is true, select two,otherwise select three


In [20]:
import tensorflow as tf
v1=tf.constant([1.0,2.0,3.0,4.0])
v2=tf.constant([4.0,3.0,2.0,1.0])

sess=tf.InteractiveSession()
print(tf.greater(v1,v2).eval())

print(tf.where(tf.greater(v1,v2),v1,v2).eval())

sess.close()

[False False  True  True]
[ 4.  3.  3.  4.]


In [25]:
import tensorflow as tf
from numpy.random import RandomState

batch_size=8

x=tf.placeholder(tf.float32,shape=(None,2),name='x-input')

y_=tf.placeholder(tf.float32,shape=(None,1),name='y-input')

#define forward
w1=tf.Variable(tf.random_normal([2,1],stddev=1,seed=1))
y=tf.matmul(x,w1)

loss_less=10
loss_more=1

loss=tf.reduce_sum(tf.where(tf.greater(y,y_),(y-y_)*loss_more,(y_-y)*loss_less))

train_step=tf.train.AdamOptimizer(0.001).minimize(loss)


rdm=RandomState(1)
dataset_size=128
X=rdm.rand(dataset_size,2)


Y=[[x1+x2+rdm.rand()/10.0-0.05] for (x1,x2) in X]
#train the net
with tf.Session() as sess:
    init_op=tf.global_variables_initializer()
    sess.run(init_op)
    STEPS=5000
    for i in range(STEPS):
        start=(i*batch_size)%dataset_size
        end=min(start+batch_size,dataset_size)
        
        sess.run(train_step,feed_dict={x:X[start:end],y_:Y[start:end]})
        print(sess.run(w1))

[[-0.81031823]
 [ 1.4855988 ]]
[[-0.8093366]
 [ 1.4865911]]
[[-0.80838311]
 [ 1.48758912]]
[[-0.80742168]
 [ 1.48854196]]
[[-0.80644417]
 [ 1.4894979 ]]
[[-0.80545688]
 [ 1.49047196]]
[[-0.80446237]
 [ 1.49145281]]
[[-0.8034634 ]
 [ 1.49243844]]
[[-0.80245554]
 [ 1.49342489]]
[[-0.80146426]
 [ 1.49441588]]
[[-0.80048096]
 [ 1.49542165]]
[[-0.79950386]
 [ 1.4964081 ]]
[[-0.79850495]
 [ 1.49741769]]
[[-0.79752892]
 [ 1.49840248]]
[[-0.79654419]
 [ 1.4994123 ]]
[[-0.79556257]
 [ 1.50043571]]
[[-0.79462433]
 [ 1.50143182]]
[[-0.79369748]
 [ 1.50242686]]
[[-0.79274493]
 [ 1.50342429]]
[[-0.79180086]
 [ 1.50438201]]
[[-0.79083252]
 [ 1.50532436]]
[[-0.78985554]
 [ 1.50629151]]
[[-0.78887033]
 [ 1.50725818]]
[[-0.78787929]
 [ 1.50822437]]
[[-0.78687394]
 [ 1.50918674]]
[[-0.78588563]
 [ 1.51015079]]
[[-0.78490686]
 [ 1.51113391]]
[[-0.7839362 ]
 [ 1.51209509]]
[[-0.78293514]
 [ 1.51309192]]
[[-0.7819587 ]
 [ 1.51406181]]
[[-0.78097296]
 [ 1.51506674]]
[[-0.77999133]
 [ 1.51609015]]
[[-0.77905

[[-0.46796134]
 [ 1.803509  ]]
[[-0.46703246]
 [ 1.80431247]]
[[-0.4661063 ]
 [ 1.80513859]]
[[-0.46519732]
 [ 1.80595922]]
[[-0.4643333 ]
 [ 1.80677438]]
[[-0.46348909]
 [ 1.80759346]]
[[-0.46260786]
 [ 1.80841839]]
[[-0.46173176]
 [ 1.80921721]]
[[-0.46081138]
 [ 1.81001782]]
[[-0.45989332]
 [ 1.81081283]]
[[-0.45895445]
 [ 1.81163442]]
[[-0.45799872]
 [ 1.81247962]]
[[-0.45701665]
 [ 1.81333029]]
[[-0.45607316]
 [ 1.81412315]]
[[-0.45515203]
 [ 1.81491864]]
[[-0.45424142]
 [ 1.81568253]]
[[-0.45327473]
 [ 1.8165369 ]]
[[-0.45234463]
 [ 1.81734407]]
[[-0.45141721]
 [ 1.81817412]]
[[-0.45050699]
 [ 1.81899869]]
[[-0.44964769]
 [ 1.81980479]]
[[-0.44880766]
 [ 1.82061625]]
[[-0.44792995]
 [ 1.82143486]]
[[-0.44705686]
 [ 1.82222831]]
[[-0.44613892]
 [ 1.82302451]]
[[-0.44522291]
 [ 1.82381594]]
[[-0.44428566]
 [ 1.82463503]]
[[-0.44333118]
 [ 1.82547855]]
[[-0.44235182]
 [ 1.82632375]]
[[-0.44141069]
 [ 1.82711172]]
[[-0.44049159]
 [ 1.82790339]]
[[-0.43958265]
 [ 1.82866406]]
[[-0.438

 [ 2.03253794]]
[[-0.17920658]
 [ 2.0330286 ]]
[[-0.17845017]
 [ 2.03352761]]
[[-0.17769419]
 [ 2.03402281]]
[[-0.17690364]
 [ 2.03452611]]
[[-0.17612825]
 [ 2.03501058]]
[[-0.17539322]
 [ 2.03547239]]
[[-0.17466179]
 [ 2.03590226]]
[[-0.1738777 ]
 [ 2.03642488]]
[[-0.1731136 ]
 [ 2.03692484]]
[[-0.17238092]
 [ 2.03740644]]
[[-0.17168429]
 [ 2.03785253]]
[[-0.1710573 ]
 [ 2.03824091]]
[[-0.17046824]
 [ 2.03861427]]
[[-0.16982958]
 [ 2.03901744]]
[[-0.16919264]
 [ 2.03940296]]
[[-0.16847576]
 [ 2.03984761]]
[[-0.16774888]
 [ 2.04031014]]
[[-0.16700716]
 [ 2.0407846 ]]
[[-0.166264 ]
 [ 2.0412581]]
[[-0.16548435]
 [ 2.04174256]]
[[-0.16471845]
 [ 2.04221034]]
[[-0.16399176]
 [ 2.04265738]]
[[-0.16326745]
 [ 2.04307413]]
[[-0.16248907]
 [ 2.04358625]]
[[-0.1617298 ]
 [ 2.04407716]]
[[-0.16100124]
 [ 2.0445509 ]]
[[-0.16030811]
 [ 2.04499006]]
[[-0.15968429]
 [ 2.04537225]]
[[-0.15909795]
 [ 2.04574013]]
[[-0.15846115]
 [ 2.046139  ]]
[[-0.15782554]
 [ 2.04652095]]
[[-0.15710907]
 [ 2.04696

[[ 0.05621369]
 [ 2.15753984]]
[[ 0.05674135]
 [ 2.15774012]]
[[ 0.05735041]
 [ 2.15800142]]
[[ 0.05796528]
 [ 2.15827918]]
[[ 0.0586181]
 [ 2.158602 ]]
[[ 0.05929144]
 [ 2.15895081]]
[[ 0.05998962]
 [ 2.15929461]]
[[ 0.06065264]
 [ 2.15959477]]
[[ 0.06126766]
 [ 2.15986443]]
[[ 0.06190092]
 [ 2.16012502]]
[[ 0.06252661]
 [ 2.16040206]]
[[ 0.06311978]
 [ 2.16063547]]
[[ 0.0636714 ]
 [ 2.16083288]]
[[ 0.06421015]
 [ 2.16102624]]
[[ 0.06469472]
 [ 2.16118336]]
[[ 0.06512405]
 [ 2.16130257]]
[[ 0.06563456]
 [ 2.16149497]]
[[ 0.06616491]
 [ 2.16169667]]
[[ 0.06677717]
 [ 2.16196012]]
[[ 0.0673953 ]
 [ 2.16224027]]
[[ 0.06805163]
 [ 2.16256571]]
[[ 0.06872863]
 [ 2.16291761]]
[[ 0.06943063]
 [ 2.16326451]]
[[ 0.07009729]
 [ 2.1635673 ]]
[[ 0.07071568]
 [ 2.16383934]]
[[ 0.07135244]
 [ 2.16410208]]
[[ 0.0719816]
 [ 2.1643815]]
[[ 0.07257806]
 [ 2.16461706]]
[[ 0.07313273]
 [ 2.16481638]]
[[ 0.07367447]
 [ 2.16501164]]
[[ 0.07416173]
 [ 2.16517019]]
[[ 0.07459345]
 [ 2.16529059]]
[[ 0.0751068

[[ 0.24292073]
 [ 2.21027398]]
[[ 0.24339129]
 [ 2.21032739]]
[[ 0.24383511]
 [ 2.21035957]]
[[ 0.24424714]
 [ 2.21036386]]
[[ 0.24461071]
 [ 2.21033978]]
[[ 0.24492994]
 [ 2.21029043]]
[[ 0.24531534]
 [ 2.21029758]]
[[ 0.24574392]
 [ 2.21033931]]
[[ 0.24625519]
 [ 2.21044135]]
[[ 0.24675226]
 [ 2.21054125]]
[[ 0.2472322 ]
 [ 2.21063566]]
[[ 0.24768163]
 [ 2.21070433]]
[[ 0.24819314]
 [ 2.21080327]]
[[ 0.24869357]
 [ 2.21088052]]
[[ 0.24916498]
 [ 2.21094918]]
[[ 0.2496818 ]
 [ 2.21103311]]
[[ 0.25016949]
 [ 2.21111536]]
[[ 0.25064313]
 [ 2.21116924]]
[[ 0.25108987]
 [ 2.21120167]]
[[ 0.2515046 ]
 [ 2.21120596]]
[[ 0.25187057]
 [ 2.21118164]]
[[ 0.2521919 ]
 [ 2.21113181]]
[[ 0.25257984]
 [ 2.21113896]]
[[ 0.25301123]
 [ 2.21118116]]
[[ 0.25348249]
 [ 2.21124125]]
[[ 0.2539438 ]
 [ 2.21130347]]
[[ 0.25439176]
 [ 2.21136403]]
[[ 0.25481251]
 [ 2.21140194]]
[[ 0.25529897]
 [ 2.2114737 ]]
[[ 0.25577712]
 [ 2.21152639]]
[[ 0.25622863]
 [ 2.21157289]]
[[ 0.2567282 ]
 [ 2.21163702]]
[[ 0.257

[[ 0.36446232]
 [ 2.20383954]]
[[ 0.36483735]
 [ 2.20376039]]
[[ 0.36527944]
 [ 2.20371509]]
[[ 0.36565325]
 [ 2.20363426]]
[[ 0.36601976]
 [ 2.20352674]]
[[ 0.36637262]
 [ 2.2034111 ]]
[[ 0.36670443]
 [ 2.20327735]]
[[ 0.36699471]
 [ 2.20312381]]
[[ 0.36724234]
 [ 2.20294905]]
[[ 0.36752689]
 [ 2.20280719]]
[[ 0.36783969]
 [ 2.20268607]]
[[ 0.36821502]
 [ 2.2026031 ]]
[[ 0.36857343]
 [ 2.20251751]]
[[ 0.36892393]
 [ 2.20243382]]
[[ 0.36925918]
 [ 2.20233893]]
[[ 0.3696827 ]
 [ 2.20229793]]
[[ 0.37010938]
 [ 2.20224667]]
[[ 0.37048689]
 [ 2.20216656]]
[[ 0.37093189]
 [ 2.20212078]]
[[ 0.37130815]
 [ 2.20203924]]
[[ 0.37167707]
 [ 2.20193076]]
[[ 0.37203225]
 [ 2.20181394]]
[[ 0.37236625]
 [ 2.20167875]]
[[ 0.37265843]
 [ 2.20152354]]
[[ 0.3729077 ]
 [ 2.20134711]]
[[ 0.37319413]
 [ 2.20120406]]
[[ 0.37350902]
 [ 2.20108175]]
[[ 0.37388685]
 [ 2.20099807]]
[[ 0.37424764]
 [ 2.20091176]]
[[ 0.3746005 ]
 [ 2.20082736]]
[[ 0.37493801]
 [ 2.20073152]]
[[ 0.37536439]
 [ 2.20069003]]
[[ 0.375

[[ 0.48310778]
 [ 2.15513945]]
[[ 0.48340479]
 [ 2.15495634]]
[[ 0.48376343]
 [ 2.15480423]]
[[ 0.48413825]
 [ 2.15465045]]
[[ 0.48446807]
 [ 2.1544714 ]]
[[ 0.48484549]
 [ 2.15431404]]
[[ 0.48515728]
 [ 2.15412426]]
[[ 0.48547253]
 [ 2.15391135]]
[[ 0.48578274]
 [ 2.15369678]]
[[ 0.48607829]
 [ 2.15346789]]
[[ 0.48633459]
 [ 2.15322185]]
[[ 0.4865495 ]
 [ 2.15295625]]
[[ 0.48677239]
 [ 2.15270305]]
[[ 0.4870384 ]
 [ 2.15248299]]
[[ 0.48738599]
 [ 2.15231633]]
[[ 0.48767722]
 [ 2.15211678]]
[[ 0.48797151]
 [ 2.15192938]]
[[ 0.48825914]
 [ 2.15173697]]
[[ 0.48860994]
 [ 2.15157676]]
[[ 0.48897809]
 [ 2.15141535]]
[[ 0.48930183]
 [ 2.15122914]]
[[ 0.48967433]
 [ 2.15106535]]
[[ 0.4899815 ]
 [ 2.15086937]]
[[ 0.49029285]
 [ 2.1506505 ]]
[[ 0.49059972]
 [ 2.15043044]]
[[ 0.49089238]
 [ 2.15019631]]
[[ 0.491146  ]
 [ 2.14994526]]
[[ 0.49135837]
 [ 2.14967489]]
[[ 0.49157917]
 [ 2.14941716]]
[[ 0.49184376]
 [ 2.14919305]]
[[ 0.49219081]
 [ 2.14902306]]
[[ 0.49248141]
 [ 2.14882016]]
[[ 0.492

 [ 2.0693233 ]]
[[ 0.57856387]
 [ 2.06900406]]
[[ 0.57877475]
 [ 2.06865501]]
[[ 0.57898325]
 [ 2.06829858]]
[[ 0.57915968]
 [ 2.06793046]]
[[ 0.57930028]
 [ 2.06754732]]
[[ 0.57946068]
 [ 2.06718588]]
[[ 0.57968014]
 [ 2.0668695 ]]
[[ 0.57997447]
 [ 2.06660151]]
[[ 0.5802145 ]
 [ 2.06630206]]
[[ 0.58040601]
 [ 2.06597948]]
[[ 0.58060443]
 [ 2.06566095]]
[[ 0.58088863]
 [ 2.06538963]]
[[ 0.58116519]
 [ 2.06510019]]
[[ 0.58140528]
 [ 2.06479144]]
[[ 0.58171451]
 [ 2.06451821]]
[[ 0.5819605 ]
 [ 2.06421494]]
[[ 0.58222193]
 [ 2.06389213]]
[[ 0.58243221]
 [ 2.06353927]]
[[ 0.58264029]
 [ 2.06317925]]
[[ 0.5828163 ]
 [ 2.06280756]]
[[ 0.58295643]
 [ 2.06242085]]
[[ 0.58311659]
 [ 2.06205606]]
[[ 0.58333635]
 [ 2.06173682]]
[[ 0.58363158]
 [ 2.06146646]]
[[ 0.5838722 ]
 [ 2.06116438]]
[[ 0.58406407]
 [ 2.06083894]]
[[ 0.58426303]
 [ 2.06051779]]
[[ 0.58454841]
 [ 2.06024408]]
[[ 0.58482617]
 [ 2.05995226]]
[[ 0.58506727]
 [ 2.05964088]]
[[ 0.58537799]
 [ 2.05936527]]
[[ 0.58562511]
 [ 2.059

[[ 0.65056795]
 [ 1.93897295]]
[[ 0.65083176]
 [ 1.93857646]]
[[ 0.65104055]
 [ 1.93814778]]
[[ 0.65125   ]
 [ 1.93771291]]
[[ 0.6514256 ]
 [ 1.93726671]]
[[ 0.65156263]
 [ 1.93680489]]
[[ 0.65172493]
 [ 1.93636978]]
[[ 0.65195763]
 [ 1.93598878]]
[[ 0.65220463]
 [ 1.93561578]]
[[ 0.65239823]
 [ 1.93521237]]
[[ 0.65254408]
 [ 1.93478751]]
[[ 0.65270543]
 [ 1.93437254]]
[[ 0.6529724]
 [ 1.9340167]]
[[ 0.65323663]
 [ 1.93364394]]
[[ 0.6534642 ]
 [ 1.93325245]]
[[ 0.65377641]
 [ 1.93290544]]
[[ 0.65402013]
 [ 1.93252647]]
[[ 0.65428555]
 [ 1.93212736]]
[[ 0.6544956 ]
 [ 1.93169594]]
[[ 0.65470636]
 [ 1.93125832]]
[[ 0.65488303]
 [ 1.93080926]]
[[ 0.65502089]
 [ 1.93034434]]
[[ 0.65518421]
 [ 1.92990649]]
[[ 0.65541834]
 [ 1.92952299]]
[[ 0.65566689]
 [ 1.9291476 ]]
[[ 0.65586162]
 [ 1.92874157]]
[[ 0.65600836]
 [ 1.92831397]]
[[ 0.65617067]
 [ 1.92789626]]
[[ 0.65643924]
 [ 1.92753816]]
[[ 0.65670508]
 [ 1.927163  ]]
[[ 0.65693408]
 [ 1.92676902]]
[[ 0.6572482 ]
 [ 1.92641973]]
[[ 0.65749

[[ 0.73130083]
 [ 1.77675474]]
[[ 0.73149794]
 [ 1.77623224]]
[[ 0.73166049]
 [ 1.77569902]]
[[ 0.73178267]
 [ 1.77514982]]
[[ 0.73193735]
 [ 1.77463329]]
[[ 0.73217577]
 [ 1.77418041]]
[[ 0.73243344]
 [ 1.77373827]]
[[ 0.73263234]
 [ 1.7732625 ]]
[[ 0.73277891]
 [ 1.77276325]]
[[ 0.7329452 ]
 [ 1.77227652]]
[[ 0.73316109]
 [ 1.77182055]]
[[ 0.73338276]
 [ 1.77134979]]
[[ 0.73357058]
 [ 1.77086174]]
[[ 0.73386264]
 [ 1.77042866]]
[[ 0.73408276]
 [ 1.76996231]]
[[ 0.73433369]
 [ 1.76947594]]
[[ 0.73452646]
 [ 1.76895511]]
[[ 0.73472476]
 [ 1.76842976]]
[[ 0.73488832]
 [ 1.76789343]]
[[ 0.73501128]
 [ 1.76734114]]
[[ 0.73516685]
 [ 1.76682162]]
[[ 0.7354067 ]
 [ 1.76636624]]
[[ 0.73566592]
 [ 1.76592159]]
[[ 0.73586601]
 [ 1.76544321]]
[[ 0.73601341]
 [ 1.76494122]]
[[ 0.73618072]
 [ 1.76445174]]
[[ 0.73639792]
 [ 1.76399326]]
[[ 0.73662096]
 [ 1.76351988]]
[[ 0.73680991]
 [ 1.7630291 ]]
[[ 0.73710376]
 [ 1.76259351]]
[[ 0.73732519]
 [ 1.76212454]]
[[ 0.73757762]
 [ 1.76163542]]
[[ 0.737

[[ 0.8048355 ]
 [ 1.58319354]]
[[ 0.8050037 ]
 [ 1.58259547]]
[[ 0.80512756]
 [ 1.58197916]]
[[ 0.80529004]
 [ 1.58139932]]
[[ 0.80554956]
 [ 1.58089113]]
[[ 0.80583233]
 [ 1.58039474]]
[[ 0.80604917]
 [ 1.57986021]]
[[ 0.80620718]
 [ 1.57929897]]
[[ 0.80638874]
 [ 1.57875168]]
[[ 0.80656946]
 [ 1.57821369]]
[[ 0.80676335]
 [ 1.57766151]]
[[ 0.80692446]
 [ 1.57709193]]
[[ 0.80720997]
 [ 1.57658613]]
[[ 0.80741805]
 [ 1.57604468]]
[[ 0.80768383]
 [ 1.57550561]]
[[ 0.80788523]
 [ 1.57492673]]
[[ 0.80809486]
 [ 1.57434189]]
[[ 0.80826646]
 [ 1.57374406]]
[[ 0.80839324]
 [ 1.57312751]]
[[ 0.80855858]
 [ 1.57254732]]
[[ 0.80882132]
 [ 1.57203889]]
[[ 0.80910724]
 [ 1.57154214]]
[[ 0.80932671]
 [ 1.57100689]]
[[ 0.80948693]
 [ 1.57044458]]
[[ 0.80967063]
 [ 1.5698961 ]]
[[ 0.80985343]
 [ 1.56935692]]
[[ 0.81004936]
 [ 1.56880319]]
[[ 0.81021219]
 [ 1.56823194]]
[[ 0.81049997]
 [ 1.5677247 ]]
[[ 0.81070983]
 [ 1.56718147]]
[[ 0.81097764]
 [ 1.5666405 ]]
[[ 0.81118071]
 [ 1.56605959]]
[[ 0.811

[[ 0.87510943]
 [ 1.36909223]]
[[ 0.8753224 ]
 [ 1.36845493]]
[[ 0.8755461 ]
 [ 1.36781061]]
[[ 0.87572813]
 [ 1.3671515 ]]
[[ 0.87586069]
 [ 1.36647141]]
[[ 0.8760379 ]
 [ 1.36583126]]
[[ 0.87625802]
 [ 1.36524022]]
[[ 0.87651193]
 [ 1.36466479]]
[[ 0.87669766]
 [ 1.36404932]]
[[ 0.87684315]
 [ 1.36343431]]
[[ 0.87701875]
 [ 1.36283386]]
[[ 0.87719649]
 [ 1.36224282]]
[[ 0.87739193]
 [ 1.36163521]]
[[ 0.87755257]
 [ 1.36100757]]
[[ 0.87785673]
 [ 1.36045027]]
[[ 0.87807494]
 [ 1.35985267]]
[[ 0.87836051]
 [ 1.35925722]]
[[ 0.87857461]
 [ 1.35861719]]
[[ 0.8787995]
 [ 1.35797  ]]
[[ 0.87898248]
 [ 1.35730803]]
[[ 0.87911576]
 [ 1.35662496]]
[[ 0.87929392]
 [ 1.35598207]]
[[ 0.87951517]
 [ 1.3553884 ]]
[[ 0.87977046]
 [ 1.35481048]]
[[ 0.87995714]
 [ 1.35419226]]
[[ 0.88010341]
 [ 1.35357451]]
[[ 0.8802799 ]
 [ 1.35297143]]
[[ 0.88045859]
 [ 1.35237789]]
[[ 0.88065505]
 [ 1.35176766]]
[[ 0.88081652]
 [ 1.35113728]]
[[ 0.88112229]
 [ 1.35057759]]
[[ 0.88134164]
 [ 1.34997749]]
[[ 0.88162

[[ 0.95162427]
 [ 1.14491844]]
[[ 0.95183873]
 [ 1.14438474]]
[[ 0.9519794 ]
 [ 1.14384508]]
[[ 0.95207125]
 [ 1.14327395]]
[[ 0.9522137 ]
 [ 1.14275706]]
[[ 0.95251918]
 [ 1.14230025]]
[[ 0.95273238]
 [ 1.14178431]]
[[ 0.9530465 ]
 [ 1.14133179]]
[[ 0.95328158]
 [ 1.14081085]]
[[ 0.95352888]
 [ 1.14026439]]
[[ 0.95372993]
 [ 1.13968575]]
[[ 0.95387596]
 [ 1.13906968]]
[[ 0.95407206]
 [ 1.1384846 ]]
[[ 0.95434296]
 [ 1.13802314]]
[[ 0.95464909]
 [ 1.13756025]]
[[ 0.95487684]
 [ 1.13703668]]
[[ 0.95505762]
 [ 1.13649857]]
[[ 0.95527017]
 [ 1.13596284]]
[[ 0.95540887]
 [ 1.13542104]]
[[ 0.95549887]
 [ 1.13484764]]
[[ 0.9556399 ]
 [ 1.13432872]]
[[ 0.95594472]
 [ 1.13387012]]
[[ 0.95623749]
 [ 1.13347626]]
[[ 0.95662367]
 [ 1.13313365]]
[[ 0.95692343]
 [ 1.13271105]]
[[ 0.95722914]
 [ 1.13225281]]
[[ 0.95748264]
 [ 1.13175321]]
[[ 0.95767576]
 [ 1.13120782]]
[[ 0.95791447]
 [ 1.13068628]]
[[ 0.95822418]
 [ 1.13028228]]
[[ 0.95856547]
 [ 1.12987101]]
[[ 0.95882469]
 [ 1.12939334]]
[[ 0.959

[[ 1.01921654]
 [ 1.04276097]]
[[ 1.01909697]
 [ 1.04263496]]
[[ 1.01897943]
 [ 1.04256892]]
[[ 1.01902878]
 [ 1.04264033]]
[[ 1.01906705]
 [ 1.04264867]]
[[ 1.01918101]
 [ 1.04284477]]
[[ 1.01930106]
 [ 1.04325163]]
[[ 1.01935613]
 [ 1.04349959]]
[[ 1.0194453 ]
 [ 1.04364228]]
[[ 1.01950157]
 [ 1.04368067]]
[[ 1.01957476]
 [ 1.04374707]]
[[ 1.0195787 ]
 [ 1.04370654]]
[[ 1.01961887]
 [ 1.04386175]]
[[ 1.01972413]
 [ 1.04395235]]
[[ 1.01980543]
 [ 1.04413247]]
[[ 1.01985168]
 [ 1.04422545]]
[[ 1.0198437 ]
 [ 1.04422688]]
[[ 1.01978683]
 [ 1.04419506]]
[[ 1.01969695]
 [ 1.04407752]]
[[ 1.01968265]
 [ 1.04396904]]
[[ 1.01966345]
 [ 1.04381549]]
[[ 1.01966858]
 [ 1.04375196]]
[[ 1.01969075]
 [ 1.04392552]]
[[ 1.01965725]
 [ 1.04396367]]
[[ 1.01958144]
 [ 1.04387462]]
[[ 1.01948893]
 [ 1.04370451]]
[[ 1.01942837]
 [ 1.04358315]]
[[ 1.01931143]
 [ 1.0433737 ]]
[[ 1.019243  ]
 [ 1.04337692]]
[[ 1.01925099]
 [ 1.04333067]]
[[ 1.01924467]
 [ 1.04338753]]
[[ 1.01921189]
 [ 1.04336965]]
[[ 1.019

[[ 1.01940274]
 [ 1.04290748]]
[[ 1.01945662]
 [ 1.04283655]]
[[ 1.01953042]
 [ 1.04284477]]
[[ 1.0196166 ]
 [ 1.04307497]]
[[ 1.01963401]
 [ 1.04316807]]
[[ 1.01959813]
 [ 1.04313254]]
[[ 1.01953864]
 [ 1.04301369]]
[[ 1.01951063]
 [ 1.0429374 ]]
[[ 1.01941502]
 [ 1.04277194]]
[[ 1.01937056]
 [ 1.04280818]]
[[ 1.01940894]
 [ 1.04279339]]
[[ 1.01942825]
 [ 1.04287517]]
[[ 1.01941514]
 [ 1.04288208]]
[[ 1.01934695]
 [ 1.04280889]]


In [ ]:
batch_size=n

x=tf.placeholder(tf.float32,shape=(batch_size,2),name='x-input')
y_=tf.placeholder(tf.float32,shape=(batch_size,1),name='y-input')

#define loss
loss=...
train_step=tf.train.AdamOptimizer(0.001).minimize(loss)

#train the net
with tf.Session() as sess:
    #parament initialize
    ...
    for i in range(STEPS):
        currnet_X,current_Y=...
        sess.run(train_step,feed_dict={x:current_X,y_:current_Y})
        

In [ ]:
#decay
decayed_learning_rate=learning_rate*decay_rate^(global_step/decay_steps)


In [ ]:
#one way to solve overfiting
import tensorflow as tf

#get one layer'e weight
def get_weight(shape,lambda):
    var=tf.Variable(tf.random_normal(shape),dtype=tf.float32)
    tf.add_to_collection('loss',tf.contrib.layer.l2_regularizer(lambda)(var))
    return var

x=tf.placeholder(tf.float32,shape=(None,2))
y_=tf.placeholder(tf.float32,shape=(None,1))
batch_size=8

#define node in each layer
layer_dimension=[2,10,10,10,1]
#deine the layers
in_dimension=layer_dimension[0]

#create 5 layers
for i in range(1,n_layers):
    out_dimension=layer_dimension[i]
    
    weight=get_weight([in_dimension,out_dimension],0.001)
    bias=tf.Variable(tf.constant(0.1,shape=[out_dimension]))
    
    #use relu
    cur_layer=tf.nn.relu(tf.matmul(cur_layer,weight)+bias)
    #update node
    in_dimension=layer_dimension[i]
    
mse_loss=tf.reduce_mean(tf.square(y_-cur_layer))

tf.add_to_collection('losses',mse_loss)

#return a list

loss=tf.add_n(tf.get_collection('losses'))


In [5]:
# an example about ExpoentialMovingAverage
import tensorflow as tf
v1=tf.Variable(0,dtype=tf.float32)
step=tf.Variable(0,trainable=False)

#define a class
ema=tf.train.ExponentialMovingAverage(0.99,step)

maintain_average_op=ema.apply([v1])

with tf.Session() as sess:
    init_op=tf.global_variables_initializer()
    sess.run(init_op)
    
    print(sess.run([v1,ema.average(v1)])
    
    sess.run(tf.assign(v1,5))
    
    sess.run(maintain_average_op)
    print(sess.run([v1,ema.average(v1)]))
    
    sess.run(tf.assign(step,10000))
    sess.run(tf.assign(v1,10))
    
    sess.run(maintain_averages_op)
    
    print(sess.run([v1,ema.average(v1)]))
    
    sess.run(maintain_averages_op)
    print(sess.run([v1,ema.average(v1)]))

SyntaxError: invalid syntax (<ipython-input-5-b966a759e84b>, line 17)